#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn lint:fix
yarn format:staged

# Reference : https://docs.onruntime.com/contributing/commits
bash $(dirname -- "$0")/scripts/validate-branch-name.sh
